### ISSUE TITLE
Cannot receive notifications when the app was killed on iOS

### ISSUE THREAD

**Issue by ghost** [cometchat-pro/react-native-chat-push-notification-app#1]
### On iOS, it works only when the app is in foreground and background but it fails to get notifications if it was killed.

> It works perfectly fine on Android. Notifications can be received when the app is in foreground, background and quit state. 

> On iOS, it works only when the app is in foreground and background but it fails to get notifications if it was killed. This situation also happens in your sample app.

### Expected behaviour: Notifications can be received when the app was killed on iOS

> Notifications can be received when the app was killed on iOS

### Reproduction

> Everything the same in your master branch

### Environment

> Everything the same in your master branch

**Comment by prathamesh-cometchat** [comment]
We have added a Notifee background handler in index.js. Please try again.

**Comment by mayur-bhandari** [comment]
Hello @Matt-AppicIDEA ,

If you are testing push notifications on iOS 14.3, then you would have to update the firebase-ios-sdk. Please follow the below steps.
​
Step 1: In the PodFile, you can see a variable is used to override the ios-sdk version  $FirebaseSDKVersion. Please change it to 7.1.0
​
Step 2: Delete Podfile.lock and run pod install to install the latest version.
​
Step 3: Uninstall the app from the device, clear derived data, and run the app again.

**Comment by proveshapyne** [comment]
Hi @Matt-AppicIDEA,

Hope you found this helpful. I am closing this ticket due to inactivity. 

Please feel free to create a new ticket or reach out to us at help@cometchat.com if you need more assistance or have any questions.

Regards,
Provesha
