### ISSUE TITLE
Is there any way to enable/disable push notification for specific user?

### ISSUE THREAD

**Issue by gajjartejas** [cometchat-pro/react-native-chat-push-notification-app#2]
### Describe the problem
Is there any way to enable/disable push notification for specific user?

**Comment by prathamesh-cometchat** [comment]
We have Mute functionality that enables the end-user to set preferences and stop receiving Push Notifications for calls and/or chat messages from certain users and/or groups.

You can learn more here: https://www.cometchat.com/docs/extensions/mute-functionality
