### ISSUE TITLE
Possible Unhandled Promise Rejection (id: 0): TypeError: Cannot convert null value to object while registering FCM token

### ISSUE THREAD

**Issue by Sandeep145XamRN** [cometchat-pro/react-native-chat-push-notification-app#3]
### Describe the problem
> Unable to register FCM token to comet-chat.

```
  useEffect(() => {
    //comet chat changes/additions
    var appSetting = new CometChat.AppSettingsBuilder()
      .subscribePresenceForAllUsers()
      .setRegion(Config.COMETCHAT_CONSTANTS.REGION)
      .build();
    //cometchat initialize
    CometChat.init(Config.COMETCHAT_CONSTANTS.APP_ID, appSetting)
      .then(() => {
        if (CometChat.setSource) {
          CometChat.setSource('ui-kit', Platform.OS, 'react-native');
        }
        CometChat.login(userData?.uuid, Config.COMETCHAT_CONSTANTS.AUTH_KEY).then((user) => {
          registerForFCM()
        }).catch(err => console.warn('login failed', err));
      })
      .catch(() => {
        return null;
      });

  }, []);

  const getPermissions = async () => {
    if (Platform.OS === 'android') {
      let granted = await PermissionsAndroid.requestMultiple([
        PermissionsAndroid.PERMISSIONS.CAMERA,
        PermissionsAndroid.PERMISSIONS.RECORD_AUDIO,
        PermissionsAndroid.PERMISSIONS.READ_EXTERNAL_STORAGE,
        PermissionsAndroid.PERMISSIONS.WRITE_EXTERNAL_STORAGE,
      ]);
      if (granted !== PermissionsAndroid.RESULTS.GRANTED) {
        granted = await PermissionsAndroid.requestMultiple([
          PermissionsAndroid.PERMISSIONS.CAMERA,
          PermissionsAndroid.PERMISSIONS.RECORD_AUDIO,
          PermissionsAndroid.PERMISSIONS.READ_EXTERNAL_STORAGE,
          PermissionsAndroid.PERMISSIONS.WRITE_EXTERNAL_STORAGE,
        ]);
      }
    }
  };

  const registerForFCM = async () => {
    const authStatus = await messaging().requestPermission();
    const enabled = authStatus === messaging.AuthorizationStatus.AUTHORIZED || authStatus === messaging.AuthorizationStatus.PROVISIONAL;
    if (enabled) {
      let FCMToken = await messaging().getToken();
      console.log('token:', FCMToken);
      if(FCMToken){
        let response = await CometChat.registerTokenForPushNotification(FCMToken)
        .then((res) => console.warn('res11', res))
        .catch(err => console.warn('err', err));
      console.log('register fro fcm :', response);
      }     
    }
  };
```
### Reproduction
 LOG  token: egjsV2OCRUeUxEwbja2VXp:APA91bHaadVlogmOttqP6xWzmxWpqDW1jGWU9pE59YlxLUV08SUUGSQnFkTln_F4qauBYgxnQAKEUWTr2lA_OAO-uqmdPS5HYeV9-nKWcKlAC_qYqKNWhddKlXzFrRqwDD_qK0XgueXn
 WARN  Possible Unhandled Promise Rejection (id: 0):
TypeError: Cannot convert null value to object
TypeError: Cannot convert null value to object

### Environment

 ** "react-native": "^0.70.1",**
**"@cometchat-pro/react-native-chat": "^3.0.11"**

**Comment by Sandeep145XamRN** [comment]
> Pushpsen (CometChat Team) replied:
> 
> Hi Sandeep,
> 
> If you're using the latest 3.0.11 SDK, we suggest downgrading to 3.0.10 or adding a second parameter to resolve the issue.
> 
> The code snippet will look like this:
> 
> ```
> if(FCMToken){let response = await CometChat.registerTokenForPushNotification(FCMToken).then((res) => console.warn('res11', res)).catch(err => console.warn('err', err));console.log('register fro fcm :', response);}
> ```
> 
> Also, here you have used `await` and `.then` `.catch` at the same time for registerTokenForPushNotification. We would suggest you use either one, not both.
> 
> Pushpsen Airekar Senior Software Developer CometChat

@cometchat-helpcenter-bot Thank you for the informative response. Your insights are greatly appreciated!!, I have resolved this using following code:
```
const registerForFCM = async () => {
    const authStatus = await messaging().requestPermission();
    const enabled = authStatus === messaging.AuthorizationStatus.AUTHORIZED || authStatus === messaging.AuthorizationStatus.PROVISIONAL;
    if (enabled) {      
      let FCMToken = await messaging().getToken();
     // console.warn('token is here',FCMToken)
      if (FCMToken) {
        // For FCM Token
        CometChat.callExtension('push-notification', 'POST', 'v2/tokens', {
          fcmToken: FCMToken
        })
          .then(response => {
            // Success response
            console.log('response fcm', response)
          })
          .catch(error => {
            // Error occured
            console.log('error fcm', error)
          })
      }
    }
  };
```
I would like add here additional information `registerTokenForPushNotification` method have compatibility issue with ` enableHermes: true` .

**Comment by frothAml** [comment]
If you stumble upon this, the information mentioned by @Sandeep145XamRN can be found here https://www.cometchat.com/docs/extensions/token-management

And is kind of justified here https://www.cometchat.com/docs/extensions/migration-guide-push-notifications
